name: C/C++ CI

on:
  push:
    branches: [ "main" , "draft*"]
  pull_request:
    branches: [ "main" ]

jobs:
  build-mac:

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: brew install sdl2 sdl2_ttf sdl2_image    
    - name: Check dependencies
      run: make check    
    - name: Build game
      run: make snake  
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: snake-macos
        path: snake
      
  build-linux:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev    
    - name: Build game
      run: make snake
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: snake-linux
        path: snake
